froglyn:
  coords:
    lat: ${COORDS_LAT}
    lon: ${COORDS_LON}
  openWeatherMap.api.key: ${OPEN_WEATHER_MAP_API_KEY}
  telegram:
    bot.token: ${TELEGRAM_BOT_TOKEN}
    chat.id: ${TELEGRAM_BOT_ID}
  checkAtStart: true
  sendIfNotWarn: ${SEND_IF_NOT_WARN:false}

spring:
  main:
    web-application-type: NONE
